# Generated by Django 5.0 on 2025-06-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_alter_blogs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
